### ISSUE TITLE
stuck at depnotify launch

### ISSUE THREAD

**Issue by windliyue** [macadmins/installapplications#66] opened 2020-05-15 03:01 UTC
2020-05-14 19:53:01.309 Python[95:1258] [InstallApplications] Creating DEPNotify Launcher
2020-05-14 19:53:01.309 Python[95:1258] [InstallApplications] Launching DEPNotify with: depnotifycmd = ['/usr/bin/open', '/Applications/Utilities/DEPNotify.app', '--args', '-munki']
2020-05-14 19:53:01.322 Python[95:1258] [InstallApplications] Waiting for DEPNotify script to complete
2020-05-14 19:53:01.825 Python[95:1258] [InstallApplications] Waiting for DEPNotify script to complete
2020-05-14 19:53:02.326 Python[95:1258] [InstallApplications] Waiting for DEPNotify script to complete
2020-05-14 19:53:02.827 Python[95:1258] [InstallApplications] Waiting for DEPNotify script to complete
2020-05-14 19:53:03.340 Python[95:1258] [InstallApplications] Waiting for DEPNotify script to complete
2020-05-14 19:53:03.855 Python[95:1258] [InstallApplications] Waiting for DEPNotify script to complete
2020-05-14 19:53:04.394 Python[95:1258] [InstallApplications] Waiting for DEPNotify script to complete
2020-05-14 19:53:04.973 Python[95:1258] [InstallApplications] Waiting for DEPNotify script to complete

**Comment by erikng** [comment] 2020-05-15 03:45
I need more information than this. This is usually caused by the launch agent not being properly loaded.

**Comment by windliyue** [comment] 2020-05-18 03:19
what informations do you need?

**Comment by windliyue** [comment] 2020-05-18 06:44
here is my LaunchDeamons plist configuration
![image](https://user-images.githubusercontent.com/25360973/82181884-f0b55500-9915-11ea-82a8-58d70102ce72.png)

**Comment by erikng** [comment] 2020-05-18 21:15
Are you upgrading from V1 to V2? The log location has changed for both the launch agent and launch daemon.

**Comment by windliyue** [comment] 2020-05-19 03:22
Hi Erikng,
Yes, i am using V2. it is the some error message when i leave the log location as default.

**Comment by erikng** [comment] 2020-05-19 13:11
If you can join the #installapplications slack channel https://www.macadmins.org/

The issue you are experiencing is not common and others are not seeing this issue.

**Comment by Ci7rix** [comment] 2020-08-14 11:51
Hi,
I'm experiencing the same issue with a similar configuration.
@windliyue any chance you found a solution ?
Thanks

**Comment by erikng** [comment] 2020-10-15 19:04
I have open sourced what we use internally to launch DEPNotify.

https://github.com/erikng/installapplicationsdemo/blob/master/installapplications/scripts/user/depnotify_user_launcher.py

Given that I have warned about removing support from DEPNotify on https://github.com/macadmins/installapplications/issues/41 I am going to close this ticket. Please look at the installapplications demo code for how this can be used.

**Closed by erikng** 2020-10-15 19:04 UTC
